// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIWhnRGpIQKh2uiQMasr7qHoqZanKjoos',
    appId: '1:1068716969676:web:05e517ebb022f7b03a3c69',
    messagingSenderId: '1068716969676',
    projectId: 'strava-de-gars-chaud',
    authDomain: 'strava-de-gars-chaud.firebaseapp.com',
    storageBucket: 'strava-de-gars-chaud.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8xfQQnczMQHJdQrBIlN_WgHAjvI86e-Y',
    appId: '1:1068716969676:android:a620f70bc1bf060d3a3c69',
    messagingSenderId: '1068716969676',
    projectId: 'strava-de-gars-chaud',
    storageBucket: 'strava-de-gars-chaud.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlyaSzrf8Dyye1yTr7Dlh9FeuKdlWxWnE',
    appId: '1:1068716969676:ios:b3bb333bc4a48aef3a3c69',
    messagingSenderId: '1068716969676',
    projectId: 'strava-de-gars-chaud',
    storageBucket: 'strava-de-gars-chaud.firebasestorage.app',
    iosBundleId: 'com.example.stravaDeGarsChaudV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlyaSzrf8Dyye1yTr7Dlh9FeuKdlWxWnE',
    appId: '1:1068716969676:ios:b3bb333bc4a48aef3a3c69',
    messagingSenderId: '1068716969676',
    projectId: 'strava-de-gars-chaud',
    storageBucket: 'strava-de-gars-chaud.firebasestorage.app',
    iosBundleId: 'com.example.stravaDeGarsChaudV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV-iKA25i-8S5kNT8mBou-CU9Nv4x3ATc',
    appId: '1:1068716969676:web:edf913f0c70ab87d3a3c69',
    messagingSenderId: '1068716969676',
    projectId: 'strava-de-gars-chaud',
    authDomain: 'strava-de-gars-chaud.firebaseapp.com',
    storageBucket: 'strava-de-gars-chaud.firebasestorage.app',
  );

}