// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIWhnRGpIQKh2uiQMasr7qHoqZanKjoos',
    appId: '1:1068716969676:web:05e517ebb022f7b03a3c69',
    messagingSenderId: '1068716969676',
    projectId: 'strava-de-gars-chaud',
    authDomain: 'strava-de-gars-chaud.firebaseapp.com',
    storageBucket: 'strava-de-gars-chaud.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8xfQQnczMQHJdQrBIlN_WgHAjvI86e-Y',
    appId: '1:1068716969676:android:e77a0b0c3a61f2fe3a3c69',
    messagingSenderId: '1068716969676',
    projectId: 'strava-de-gars-chaud',
    storageBucket: 'strava-de-gars-chaud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlyaSzrf8Dyye1yTr7Dlh9FeuKdlWxWnE',
    appId: '1:1068716969676:ios:7aea2626cda6effb3a3c69',
    messagingSenderId: '1068716969676',
    projectId: 'strava-de-gars-chaud',
    storageBucket: 'strava-de-gars-chaud.appspot.com',
    iosBundleId: 'com.example.strava',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlyaSzrf8Dyye1yTr7Dlh9FeuKdlWxWnE',
    appId: '1:1068716969676:ios:869e7c0af8c2725b3a3c69',
    messagingSenderId: '1068716969676',
    projectId: 'strava-de-gars-chaud',
    storageBucket: 'strava-de-gars-chaud.appspot.com',
    iosBundleId: 'com.example.strava.RunnerTests',
  );
}
